import argparse
import json
from pathlib import Path


EXPORT_KEYS = [
    "size",
    "steps",
    "frame_every",
    "domain_size",
    "gravity",
    "dt",
    "wave_amplitude",
    "peak_wavelength",
    "bandwidth",
    "wind_direction_degrees",
    "directional_spread",
    "damping",
    "seed",
    "choppiness",
    "max_surface_points",
    "foam_threshold",
    "max_foam_points",
    "foam_z_offset",
]


def load_selected_manifest_path(recommendation_json: Path) -> Path:
    recommendation = json.loads(recommendation_json.read_text(encoding="utf-8"))
    selected = recommendation.get("selected")
    if not selected:
        raise RuntimeError("Recommendation JSON does not contain a selected candidate.")
    return Path(selected["manifest"])


def command_argument_name(key: str) -> str:
    return "--" + key.replace("_", "-")


def powershell_quote(value: str) -> str:
    if any(char in value for char in " \\"):
        return f'"{value}"'
    return value


def build_export_command(parameters: dict, output_dir: Path) -> str:
    parts = [r".\.venv\Scripts\python.exe", "export_spectral_choppy_asset_bundle.py"]
    for key in EXPORT_KEYS:
        if key in parameters:
            parts.append(command_argument_name(key))
            parts.append(str(parameters[key]))
    parts.append("--output-dir")
    parts.append(str(output_dir))
    return " ".join(powershell_quote(part) for part in parts)


def build_validation_command(output_dir: Path) -> str:
    return f'.\\.venv\\Scripts\\python.exe validate_spectral_choppy_asset_bundle.py --bundle-dir {powershell_quote(str(output_dir))}'


def build_plan(
    selected_manifest_path: Path,
    output_dir: Path,
    size: int,
    steps: int,
    frame_every: int,
    max_surface_points: int,
    max_foam_points: int | None,
) -> dict:
    selected_manifest = json.loads(selected_manifest_path.read_text(encoding="utf-8"))
    parameters = dict(selected_manifest.get("simulation", {}))
    parameters["size"] = size
    parameters["steps"] = steps
    parameters["frame_every"] = frame_every
    parameters["max_surface_points"] = max_surface_points
    if max_foam_points is not None:
        parameters["max_foam_points"] = max_foam_points
    export_command = build_export_command(parameters, output_dir)
    validation_command = build_validation_command(output_dir)
    return {
        "selected_manifest": str(selected_manifest_path),
        "selected_bundle": str(selected_manifest_path.parent),
        "production_output_dir": str(output_dir),
        "parameters": parameters,
        "commands": {
            "export": export_command,
            "validate": validation_command,
        },
    }


def build_plan_report(plan: dict) -> str:
    parameters = plan["parameters"]
    lines = [
        "# Spectral Choppy Wave Production Export Plan",
        "",
        "## Source",
        "",
        f"- selected_manifest: `{plan['selected_manifest']}`",
        f"- selected_bundle: `{plan['selected_bundle']}`",
        f"- production_output_dir: `{plan['production_output_dir']}`",
        "",
        "## Commands",
        "",
        "Export:",
        "",
        "```powershell",
        plan["commands"]["export"],
        "```",
        "",
        "Validate:",
        "",
        "```powershell",
        plan["commands"]["validate"],
        "```",
        "",
        "## Parameters",
        "",
        "| Parameter | Value |",
        "| --- | ---: |",
    ]
    for key in EXPORT_KEYS:
        if key in parameters:
            lines.append(f"| `{key}` | `{parameters[key]}` |")
    return "\n".join(lines) + "\n"


def write_plan(plan: dict, output: Path) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_plan_report(plan), encoding="utf-8")
    output.with_suffix(".json").write_text(json.dumps(plan, indent=2), encoding="utf-8")
    return output


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create a high-resolution export plan from a recommended choppy wave bundle.")
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--recommendation-json", type=Path, help="Recommendation JSON generated by recommend_spectral_choppy_asset_bundle.py.")
    source.add_argument("--selected-manifest", type=Path, help="Selected bundle_manifest.json path.")
    parser.add_argument("--size", type=int, default=512, help="Production simulation grid size.")
    parser.add_argument("--steps", type=int, default=720, help="Production simulation steps.")
    parser.add_argument("--frame-every", type=int, default=24, help="Production frame interval.")
    parser.add_argument("--max-surface-points", type=int, default=256, help="Production exported surface points per axis.")
    parser.add_argument("--max-foam-points", type=int, default=None, help="Optional production max foam points per frame.")
    parser.add_argument("--production-output-dir", type=Path, default=Path("outputs/spectral_choppy_asset_bundle_production"), help="Planned production output bundle directory.")
    parser.add_argument("--output", type=Path, default=Path("outputs/spectral_choppy_production_export_plan.md"), help="Output Markdown plan path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    selected_manifest = args.selected_manifest if args.selected_manifest is not None else load_selected_manifest_path(args.recommendation_json)
    plan = build_plan(
        selected_manifest,
        output_dir=args.production_output_dir,
        size=args.size,
        steps=args.steps,
        frame_every=args.frame_every,
        max_surface_points=args.max_surface_points,
        max_foam_points=args.max_foam_points,
    )
    output = write_plan(plan, args.output)
    print(f"Saved production export plan: {output}")
    print(f"Selected manifest: {plan['selected_manifest']}")


if __name__ == "__main__":
    main()
